import { escapeHtml, publicConnectUrl, publicRepoUrl, type PublicPage } from "./public-site-config.js";
import { renderCoordinationDiagram } from "./public-site-components.js";

const configurationDisclaimer = "Available connections, rules, approval points, and actions are configured for each deployment.";

function pageIntro(eyebrow: string, heading: string, summary: string) {
  return `<section class="page-hero"><p class="section-index">${eyebrow}</p><h1>${heading}</h1><p class="lead">${summary}</p></section>`;
}

function bookingCta(event: string, heading: string) {
  return `<section class="final-cta compact"><h2>${heading}</h2><a class="button button-light" href="/workflow" data-event="${event}">Book a 20-minute call</a></section>`;
}

export function securityPage(env = process.env): PublicPage {
  const repo = publicRepoUrl(env);
  return {
    id: "security",
    title: "Private AI Workflow Security",
    summary: "See how Orkestr uses private environments, approved connections, human approval, visible history, and clear operating boundaries.",
    body: `<main id="main-content">${pageIntro("SECURITY AND CONTROL", "Your systems stay under your control.", "Orkestr is designed around a simple rule: connect only what is approved, show what is happening, and keep a person in charge of important decisions.")}
      <section class="section security-flow" aria-labelledby="security-flow-title"><div><p class="section-index">HOW CONTROL WORKS</p><h2 id="security-flow-title">Approved information in. Reviewed action out.</h2><p class="section-lead">The exact tools and rules differ by deployment, but the control pattern stays clear.</p></div>${renderCoordinationDiagram()}</section>
      <section class="section trust-section" aria-labelledby="trust-title"><div class="section-heading"><p class="section-index">THREE TRUST PRINCIPLES</p><h2 id="trust-title">Control is part of the process—not an afterthought.</h2></div><div class="trust-pillars"><article><span>01</span><h3>Private environment</h3><p>Run Orkestr in a dedicated managed environment or infrastructure your organization controls.</p></article><article><span>02</span><h3>Approved connections</h3><p>Only configured accounts and services are available to the task. Access can be reviewed and revoked.</p></article><article><span>03</span><h3>Human approval</h3><p>Important actions can pause and wait for the right person before work continues.</p></article></div></section>
      <section class="section access-comparison" aria-labelledby="access-title"><div><p class="section-index">CLEAR ACCESS BOUNDARIES</p><h2 id="access-title">What Orkestr can—and cannot—work with.</h2></div><div class="access-grid"><article class="can"><h3>Orkestr can</h3><ul><li>Use tools and accounts explicitly connected for the task</li><li>Follow configured steps and approval rules</li><li>Pause work, surface warnings, and record decisions</li><li>Show recent activity and process history</li></ul></article><article class="cannot"><h3>Orkestr is not authorized to</h3><ul><li>Access systems that have not been connected and approved</li><li>Treat one connection as unlimited access to a provider</li><li>Ignore a configured human approval point</li><li>Claim certification or compliance that has not been independently established</li></ul></article></div></section>
      <section class="section security-evidence" aria-labelledby="evidence-title"><div><p class="section-index">EVIDENCE YOU CAN INSPECT</p><h2 id="evidence-title">See the controls, history, and public core.</h2></div><div class="evidence-panel"><ul class="plain-checks"><li><strong>Status and warnings</strong><span>Operators can review process state and resource warnings.</span></li><li><strong>Decision history</strong><span>Approval points and subsequent actions remain visible in the process record.</span></li><li><strong>Public implementation</strong><span>The generic source, tests, and documentation are open for review.</span></li></ul><a class="button button-outline" href="${escapeHtml(repo)}" rel="noreferrer" data-event="security_github_click">Review the open-source core</a></div></section>
      <section class="section boundary-table" aria-labelledby="boundary-title"><div><p class="section-index">WHERE INFORMATION LIVES</p><h2 id="boundary-title">Separate public software from private operations.</h2></div><dl><div><dt>Public core</dt><dd>Generic product code, documentation, tests, and illustrative examples.</dd></div><div><dt>Private environment</dt><dd>Credentials, real configuration, browser and messaging sessions, and operational records.</dd></div><div><dt>Connected services</dt><dd>Information needed for the approved task, subject to the service provider’s own terms and controls.</dd></div></dl></section>
      <section class="section limitations"><div><p class="section-index">CURRENT LIMITS</p><h2>Important details, stated plainly.</h2></div><ul><li>Orkestr does not claim a security certification or universal regulatory compliance.</li><li>Identity, retention, network policy, backups, and recovery must be reviewed for the chosen environment.</li><li>Available connections and production readiness vary by deployment.</li><li>Generated output and important actions need an appropriate human review policy.</li></ul></section>
      ${bookingCta("book_call_security", "Want to review the control model for your task?")}
    </main>`,
  };
}

export function deploymentPage(env = process.env): PublicPage {
  const connectUrl = publicConnectUrl(env);
  return {
    id: "deployment",
    title: "Private AI Deployment Options",
    summary: "Compare a managed private Orkestr environment with deployment in infrastructure your organization controls, including responsibilities and rollout steps.",
    body: `<main id="main-content">${pageIntro("DEPLOYMENT OPTIONS", "Choose where Orkestr runs.", "Use a dedicated environment operated with you, or install Orkestr in infrastructure your organization controls. Either way, access and responsibilities are agreed before live work begins.")}
      <section class="section deployment-models" aria-label="Orkestr deployment options"><article><p class="eyebrow">MANAGED PRIVATE ENVIRONMENT</p><h2>A dedicated environment, operated with you.</h2><p>Orkestr sets up and maintains the environment for the agreed task. Your team approves the connected systems, decision rules, and test examples.</p><ul class="plain-list"><li>Dedicated runtime for the agreed use</li><li>Managed updates and operational support</li><li>Customer-approved connections</li><li>Private configuration outside the public core</li></ul></article><article><p class="eyebrow">YOUR ENVIRONMENT</p><h2>Your infrastructure, with a shared implementation plan.</h2><p>Orkestr runs in infrastructure your organization controls. Your team owns the surrounding identity, network, backup, and access policies.</p><ul class="plain-list"><li>Customer-controlled infrastructure</li><li>Documented setup and handoff</li><li>Tested update and rollback process</li><li>Support responsibilities agreed in advance</li></ul></article></section>
      <section class="section rollout" aria-labelledby="rollout-title"><div><p class="section-index">A CAREFUL ROLLOUT</p><h2 id="rollout-title">Four steps from idea to live operation.</h2></div><ol class="phase-list"><li><span>01</span><div><h3>Choose the task</h3><p>Agree what should happen, what should stop, and who owns the result.</p></div></li><li><span>02</span><div><h3>Approve the connections</h3><p>Connect only the accounts and tools needed for the task.</p></div></li><li><span>03</span><div><h3>Test representative examples</h3><p>Check normal cases, exceptions, human decisions, and recovery.</p></div></li><li><span>04</span><div><h3>Release and review</h3><p>Go live deliberately, monitor the history, and keep a rollback path.</p></div></li></ol></section>
      <section class="section responsibility" aria-labelledby="responsibility-title"><div><p class="section-index">WHO HANDLES WHAT</p><h2 id="responsibility-title">Clear ownership before production.</h2></div><div class="responsibility-cards"><article><h3>The task</h3><p><strong>Orkestr:</strong> configures the steps, exceptions, and controls.</p><p><strong>Your team:</strong> approves the intent, owner, and success measure.</p></article><article><h3>The environment</h3><p><strong>Orkestr:</strong> operates the managed environment or documents the installation.</p><p><strong>Your team:</strong> approves identity, network, retention, and backup decisions.</p></article><article><h3>The connections</h3><p><strong>Orkestr:</strong> configures the agreed integration.</p><p><strong>Your team:</strong> authorizes the accounts and provider access.</p></article><article><h3>The release</h3><p><strong>Orkestr:</strong> tests, versions, monitors, and documents rollback.</p><p><strong>Your team:</strong> approves the production window and business impact.</p></article></div></section>
      <section class="section pairing-note"><div><p class="section-index">SECURE CONNECTION APPROVAL</p><h2>Application sign-in and tool connections stay separate.</h2><p>Approving a connected account uses the configured secure pairing page. It does not turn that account into open-ended access.</p></div><a class="text-link" href="${escapeHtml(connectUrl)}" rel="noreferrer">Open the configured pairing page <span aria-hidden="true">→</span></a></section>
      <section class="section limitations"><div><p class="section-index">BEFORE GO-LIVE</p><h2>The environment still needs an owner.</h2></div><ul><li>Identity, networking, retention, backup, and recovery responsibilities must be explicit.</li><li>Connections and production actions depend on the approved deployment configuration.</li><li>Self-hosting moves operational responsibility to the organization running the environment.</li><li>${configurationDisclaimer}</li></ul></section>
      ${bookingCta("book_call_deployment", "Not sure which option fits? Let’s decide together.")}
    </main>`,
  };
}

export function developersPage(env = process.env): PublicPage {
  const repo = publicRepoUrl(env);
  return {
    id: "developers",
    title: "Open-Source AI Workflow Orchestration",
    summary: "Inspect and run the Orkestr open-source core, understand its runtime and connector boundaries, and review the public-alpha quick start.",
    body: `<main id="main-content">${pageIntro("OPEN-SOURCE CORE", "Software you can inspect, run, and question.", "Orkestr keeps the generic runtime, interface, tests, and documentation public. Private deployments keep real credentials, customer configuration, and operational records outside the repository.")}
      <section class="section architecture" aria-labelledby="architecture-title"><div><p class="section-index">A SIMPLE TECHNICAL VIEW</p><h2 id="architecture-title">The agent does the work. Orkestr keeps it visible and controlled.</h2><p>Tasks live in named threads. The configured agent works in its assigned workspace. Orkestr tracks status, approvals, resources, and delivery. Approved connectors or managed browsers reach external tools.</p></div><ol class="architecture-flow"><li><span>01</span><strong>Request</strong><p>A person or approved trigger starts a task.</p></li><li><span>02</span><strong>Agent</strong><p>The configured runtime works inside its assigned workspace and permissions.</p></li><li><span>03</span><strong>Control</strong><p>Orkestr records status, warnings, approvals, and history.</p></li><li><span>04</span><strong>Connection</strong><p>An approved connector or managed browser performs the allowed action.</p></li></ol></section>
      <section class="code-section"><div><p class="section-index">PUBLIC-ALPHA QUICK START</p><h2>Run the core locally.</h2><p>Use illustrative data. Keep private configuration, secrets, and live sessions outside the repository.</p></div><pre aria-label="Orkestr quick start"><code>git clone https://github.com/otcan/orkestr.git
cd orkestr
npm ci
npm run build
npm run demo:coding-agent</code></pre><div class="actions"><a class="button button-light" href="${escapeHtml(repo)}" rel="noreferrer" data-event="github_click">View GitHub</a><a class="button button-outline" href="${escapeHtml(repo)}/tree/main/docs" rel="noreferrer" data-event="docs_click">Read the documentation</a></div></section>
      <section class="section oss-boundary"><div><p class="section-index">PUBLIC AND PRIVATE</p><h2>Know what belongs where.</h2></div><dl><div><dt>Public</dt><dd>Generic runtime, interface, connector contracts, deployment scaffolding, tests, and illustrative examples.</dd></div><div><dt>Private</dt><dd>Customer configuration, credentials, infrastructure, specialized adapters, and operational evidence.</dd></div><div><dt>Managed work</dt><dd>Process design, implementation, hardening, release, monitoring, and support within the agreed boundary.</dd></div></dl></section>
      <section class="section limitations"><div><p class="section-index">PUBLIC-ALPHA REALITY</p><h2>Build with the current limits in view.</h2></div><ul><li>Interfaces and configuration can change.</li><li>Not every connection is available or production-ready in every deployment.</li><li>Self-hosting transfers security, retention, recovery, and operations to the environment owner.</li><li>Managed implementation does not turn the open-source core into unrestricted hosted software.</li></ul></section>
      ${bookingCta("book_call_developers", "Evaluating Orkestr for a real process?")}
    </main>`,
  };
}

function useCase(id: string, label: string, title: string, intro: string, steps: string[], approval: string, outcome: string) {
  return `<article class="use-case" id="${id}"><div class="use-case-heading"><p class="eyebrow">${label}</p><h2>${title}</h2><p>${intro}</p></div><div class="use-case-body"><ol class="process-flow" aria-label="Example process">${steps.map((step, index) => `<li><span>${String(index + 1).padStart(2, "0")}</span><p>${step}</p></li>`).join("")}</ol><dl class="decision-measure"><div><dt>Manager decision</dt><dd>${approval}</dd></div><div><dt>Useful measures</dt><dd>${outcome}</dd></div></dl><p class="disclaimer">${configurationDisclaimer}</p></div></article>`;
}

export function useCasesPage(): PublicPage {
  return {
    id: "use-cases",
    title: "AI Workflow Automation Use Cases",
    summary: "Explore practical AI workflow automation examples for invoice exceptions, customer onboarding, renewals, and service escalations—with human approval.",
    body: `<main id="main-content">${pageIntro("PRACTICAL USE CASES", "Start with work your team repeats every week.", "A useful first process is easy to recognize: it happens often, information moves between tools, and a person still needs to make the important decision.")}
      <nav class="use-case-nav" aria-label="Use case shortcuts"><a href="#finance">Invoice exceptions</a><a href="#onboarding">Customer onboarding</a><a href="#revenue">Renewal preparation</a><a href="#service">Service escalations</a></nav>
      <section class="use-case-list">${useCase("finance", "FINANCE", "Invoice exception handling", "Help the finance team check invoices and focus attention on the cases that do not match.", ["Receive an invoice from an approved source", "Read the required details", "Compare them with the purchase record", "Pause when an amount, vendor, or rule does not match", "Continue or return the invoice after the decision"], "A finance owner approves or rejects the exception before posting.", "Time to decision, manual checks, repeated errors")}${useCase("onboarding", "CUSTOMER OPERATIONS", "Customer onboarding preparation", "Collect the information needed to prepare an account without granting access automatically.", ["Receive an approved account request", "Check that the required information is present", "Gather approved evidence from connected tools", "Prepare or update the onboarding record", "Pause before access or activation"], "The account owner decides whether access or activation can continue.", "Onboarding time, missing-information loops, incomplete handoffs")}${useCase("revenue", "REVENUE OPERATIONS", "Renewal preparation", "Give account owners a complete review before they decide on customer follow-up.", ["Start when an approved renewal date approaches", "Collect the agreed account and product information", "Highlight missing or conflicting details", "Prepare a short review", "Create the approved follow-up task"], "The account owner reviews the information before any external outreach.", "Preparation time, missed renewals, stale information")}${useCase("service", "SERVICE OPERATIONS", "Escalation preparation", "Help service teams collect the evidence an incident owner needs to act quickly.", ["Start when a case reaches an agreed severity or age", "Collect the relevant case history", "Check the approved runbook and recent status", "Prepare a concise evidence pack", "Route it to the incident owner"], "The incident owner chooses the response and escalation path.", "Time to triage, missing evidence, reassignment loops")}</section>
      <section class="section use-case-fit" aria-labelledby="fit-title"><div><p class="section-index">A GOOD FIRST PROCESS</p><h2 id="fit-title">Look for repeated effort and a clear decision.</h2></div><ul class="plain-checks"><li><strong>It happens often</strong><span>Your team can point to recent examples.</span></li><li><strong>It crosses tools</strong><span>People copy or check information in more than one place.</span></li><li><strong>It has an owner</strong><span>Someone is responsible for the result.</span></li><li><strong>It can be measured</strong><span>Time, delay, errors, or manual effort can be compared.</span></li></ul></section>
      ${bookingCta("book_call_use_cases", "Have a repetitive task in mind?")}
    </main>`,
  };
}
