import { publicPagePath, type PublicLocale, type PublicPage } from "./public-site-config.js";

type TrustCopy = {
  title: string; summary: string; eyebrow: string; heading: string; lead: string;
  sectionLabel: string; sectionHeading: string; cards: Array<[string, string]>;
  boundaryLabel: string; boundaryHeading: string; boundaries: Array<[string, string]>;
  limitLabel: string; limitHeading: string; limits: string[]; cta: string; book: string;
};

const securityCopy: Record<"de" | "tr", TrustCopy> = {
  de: {
    title: "Sicherheit & Zugriff bei Unternehmenssoftware", summary: "So begrenzt Orkestr Zugriffe, Verbindungen, Freigaben, Daten und Betriebsverantwortung in individuellen Software- und Automatisierungsprojekten.",
    eyebrow: "SICHERHEIT UND KONTROLLE", heading: "Ihre Systeme bleiben unter Ihrer Kontrolle.", lead: "Jedes Projekt beginnt mit klaren Nutzern, Daten, Quellen, Systemen, Berechtigungen, Verantwortlichkeiten und Betriebsgrenzen.",
    sectionLabel: "DREI KONTROLLPRINZIPIEN", sectionHeading: "Kontrolle ist Teil des Systems – kein nachträglicher Zusatz.", cards: [["Private Umgebung", "Betrieb in einer dedizierten betreuten Umgebung oder in einer Infrastruktur, die Ihre Organisation kontrolliert."], ["Begrenzte Zugriffe", "Nur die für das Projekt freigegebenen Konten, Datenquellen und Systeme werden verbunden."], ["Menschliche Freigabe", "Wichtige, externe oder irreversible Aktionen können an definierten Punkten auf eine zuständige Person warten."]],
    boundaryLabel: "KLARE VERANTWORTUNG", boundaryHeading: "Vor dem Produktivbetrieb ist geklärt, wer was kontrolliert.", boundaries: [["Öffentlicher Kern", "Generischer Produktcode, Dokumentation, Tests und illustrative Beispiele."], ["Private Umgebung", "Zugangsdaten, reale Konfiguration, Sitzungen und operative Datensätze."], ["Kundensysteme", "Nur Informationen und Aktionen, die für den vereinbarten Projektumfang erforderlich sind."]],
    limitLabel: "AKTUELLE GRENZEN", limitHeading: "Sicherheitsbehauptungen bleiben überprüfbar und konkret.", limits: ["Orkestr behauptet keine Sicherheitszertifizierung oder pauschale regulatorische Konformität.", "Identität, Aufbewahrung, Netzwerkrichtlinien, Backups und Wiederherstellung müssen für die gewählte Umgebung geprüft werden.", "Verfügbare Verbindungen und Produktionsreife unterscheiden sich je Projekt.", "Folgenreiche Ergebnisse und Aktionen benötigen eine angemessene menschliche Prüfung."],
    cta: "Möchten Sie das Zugriffsmodell für Ihr Projekt prüfen?", book: "Projektgespräch buchen",
  },
  tr: {
    title: "İş Yazılımında Güvenlik ve Erişim", summary: "Orkestr'in özel yazılım ve otomasyon projelerinde erişimi, bağlantıları, onayları, veriyi ve işletim sorumluluğunu nasıl sınırlandırdığını görün.",
    eyebrow: "GÜVENLİK VE KONTROL", heading: "Sistemleriniz sizin kontrolünüzde kalır.", lead: "Her proje; kullanıcılar, veri, kaynaklar, sistemler, izinler, sorumluluklar ve işletim sınırları açıkça tanımlanarak başlar.",
    sectionLabel: "ÜÇ KONTROL İLKESİ", sectionHeading: "Kontrol sonradan eklenmez; sistemin bir parçasıdır.", cards: [["Özel ortam", "Orkestr'i projeye özel yönetilen bir ortamda veya kuruluşunuzun kontrol ettiği altyapıda çalıştırın."], ["Sınırlı erişim", "Yalnızca proje için onaylanan hesaplar, veri kaynakları ve sistemler bağlanır."], ["İnsan onayı", "Önemli, dışa dönük veya geri alınamaz işlemler tanımlı noktalarda yetkili kişiyi bekleyebilir."]],
    boundaryLabel: "AÇIK SORUMLULUK", boundaryHeading: "Canlıya geçmeden önce kimin neyi kontrol ettiği bellidir.", boundaries: [["Açık kaynak çekirdek", "Genel ürün kodu, dokümantasyon, testler ve temsili örnekler."], ["Özel ortam", "Kimlik bilgileri, gerçek yapılandırma, oturumlar ve operasyon kayıtları."], ["Müşteri sistemleri", "Yalnızca kararlaştırılan proje kapsamı için gereken bilgi ve işlemler."]],
    limitLabel: "MEVCUT SINIRLAR", limitHeading: "Güvenlik iddiaları somut ve doğrulanabilir kalır.", limits: ["Orkestr herhangi bir güvenlik sertifikası veya genel mevzuat uyumluluğu iddiasında bulunmaz.", "Kimlik, saklama, ağ politikası, yedekleme ve kurtarma seçilen ortam için ayrıca değerlendirilmelidir.", "Kullanılabilen bağlantılar ve canlı ortam hazırlığı projeye göre değişir.", "Yüksek etkili sonuçlar ve işlemler uygun insan incelemesi gerektirir."],
    cta: "Projenizin erişim modelini birlikte değerlendirelim mi?", book: "Proje görüşmesi planla",
  },
};

const deploymentCopy: Record<"de" | "tr", TrustCopy> = {
  de: {
    title: "Bereitstellung & Betrieb individueller Software", summary: "So vereinbart Orkestr Produktionsumgebung, Verantwortlichkeiten, Einführung, Monitoring, Wartung, Zugriff und Rückfallplan für betreute Systeme.",
    eyebrow: "BEREITSTELLUNG UND BETRIEB", heading: "Wissen, wo das System läuft – und wer es am Laufen hält.", lead: "Das passende Produktionsmodell hängt vom Projekt ab. Umgebung, Daten, Identität, Releases, Monitoring, Support und Wiederherstellung werden vor dem Livebetrieb vereinbart.",
    sectionLabel: "ZWEI BETRIEBSMODELLE", sectionHeading: "Eine klare Umgebung für den vereinbarten Zweck.", cards: [["Betreute private Umgebung", "Orkestr richtet eine dedizierte Umgebung ein und betreibt sie gemeinsam mit Ihnen. Verbindungen und Entscheidungsregeln werden durch Ihr Team freigegeben."], ["Ihre Infrastruktur", "Das System läuft in einer von Ihrer Organisation kontrollierten Umgebung. Identitäts-, Netzwerk-, Backup- und Zugriffsrichtlinien bleiben bei Ihrem Team."], ["Geteilte Verantwortung", "Aufgaben, Reaktionswege, Wartungsfenster, Änderungen und Eskalation werden vor dem Produktivstart dokumentiert."]],
    boundaryLabel: "SCHRITTWEISE EINFÜHRUNG", boundaryHeading: "Vom abgegrenzten Projekt zur kontrollierten Produktion.", boundaries: [["01 · Zweck", "Ergebnis, Nutzer, Systeme, Grenzen und Erfolgskriterien festlegen."], ["02 · Verbindungen", "Nur notwendige Konten, Quellen und Dienste freigeben."], ["03 · Tests", "Normalfälle, Ausnahmen, Berechtigungen, Fehler und Wiederherstellung prüfen."], ["04 · Release", "Bewusst live gehen, überwachen und einen Rückfallweg erhalten."]],
    limitLabel: "VOR DEM START", limitHeading: "Betrieb ist Teil des Angebots.", limits: ["Produktionsverantwortung und Supportzeiten werden ausdrücklich vereinbart.", "Backups und Wiederherstellung werden passend zur Umgebung getestet.", "Änderungen durchlaufen einen sichtbaren Release- und Freigabeweg.", "Kundenspezifische Zugangsdaten und Konfiguration gehören nicht in den öffentlichen Quellcode."],
    cta: "Welches Betriebsmodell passt zu Ihrem Projekt?", book: "Projektgespräch buchen",
  },
  tr: {
    title: "Özel Yazılımı Devreye Alma ve İşletme", summary: "Orkestr'in yönetilen sistemlerde canlı ortamı, sorumlulukları, yayını, izlemeyi, bakımı, erişimi ve geri dönüş planını nasıl tanımladığını görün.",
    eyebrow: "DEVREYE ALMA VE İŞLETİM", heading: "Sistemin nerede çalıştığını ve kimin çalışır tuttuğunu bilin.", lead: "Doğru canlı ortam modeli geliştirilen sisteme bağlıdır. Ortam, veri, kimlik, yayın, izleme, destek ve kurtarma sorumlulukları canlı işletimden önce kararlaştırılır.",
    sectionLabel: "İKİ İŞLETİM MODELİ", sectionHeading: "Kararlaştırılan amaç için sınırları belli bir ortam.", cards: [["Yönetilen özel ortam", "Orkestr projeye özel ortamı kurar ve sizinle birlikte işletir. Bağlantıları ve karar kurallarını ekibiniz onaylar."], ["Sizin altyapınız", "Sistem kuruluşunuzun kontrol ettiği altyapıda çalışır. Kimlik, ağ, yedekleme ve erişim politikaları ekibinizin sorumluluğundadır."], ["Paylaşılan sorumluluk", "Görevler, müdahale yolları, bakım pencereleri, değişiklikler ve eskalasyon canlıya geçmeden belgelenir."]],
    boundaryLabel: "AŞAMALI DEVREYE ALMA", boundaryHeading: "Sınırları belli projeden kontrollü canlı işletime.", boundaries: [["01 · Amaç", "Sonucu, kullanıcıları, sistemleri, sınırları ve başarı ölçütünü belirle."], ["02 · Bağlantılar", "Yalnızca gerekli hesap, kaynak ve hizmetleri onayla."], ["03 · Test", "Normal durumları, istisnaları, izinleri, hataları ve kurtarmayı doğrula."], ["04 · Yayın", "Planlı biçimde canlıya geç, izle ve geri dönüş yolunu koru."]],
    limitLabel: "CANLIYA GEÇMEDEN ÖNCE", limitHeading: "İşletim teklifin bir parçasıdır.", limits: ["Canlı ortam sorumluluğu ve destek saatleri açıkça kararlaştırılır.", "Yedekleme ve kurtarma seçilen ortama göre test edilir.", "Değişiklikler görünür bir yayın ve onay sürecinden geçer.", "Müşteriye özel kimlik bilgileri ve yapılandırma açık kaynak depoya girmez."],
    cta: "Projenize hangi işletim modeli uygun?", book: "Proje görüşmesi planla",
  },
};

export function localizedTrustPage(pageId: "security" | "deployment", locale: "de" | "tr"): PublicPage {
  const copy = pageId === "security" ? securityCopy[locale] : deploymentCopy[locale];
  return {
    id: pageId, locale, title: copy.title, summary: copy.summary, canonicalPath: publicPagePath(pageId, locale),
    body: `<main id="main-content"><section class="page-hero"><p class="section-index">${copy.eyebrow}</p><h1>${copy.heading}</h1><p class="lead">${copy.lead}</p></section><section class="section trust-section"><div class="section-heading"><p class="section-index">${copy.sectionLabel}</p><h2>${copy.sectionHeading}</h2></div><div class="trust-pillars">${copy.cards.map(([title, text], index) => `<article><span>0${index + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section><section class="section boundary-table"><div><p class="section-index">${copy.boundaryLabel}</p><h2>${copy.boundaryHeading}</h2></div><dl>${copy.boundaries.map(([term, text]) => `<div><dt>${term}</dt><dd>${text}</dd></div>`).join("")}</dl></section><section class="section limitations"><div><p class="section-index">${copy.limitLabel}</p><h2>${copy.limitHeading}</h2></div><ul>${copy.limits.map((text) => `<li>${text}</li>`).join("")}</ul></section><section class="final-cta compact"><h2>${copy.cta}</h2><a class="button button-light" href="${publicPagePath("project", locale)}#book">${copy.book}</a></section></main>`,
  };
}

const teamCopy: Record<PublicLocale, { title: string; summary: string; eyebrow: string; heading: string; lead: string; role: string; intro: string; work: Array<[string, string]>; principle: string; transparent: string; cta: string; book: string }> = {
  en: {
    title: "Team", summary: "Meet Oğuzcan Ünver, the founder leading Orkestr project discovery, architecture, implementation, deployment, and managed operation.", eyebrow: "TEAM", heading: "Orkestr is led by Oğuzcan Ünver.", lead: "One accountable founder from the first conversation through the operating system.", role: "Founder · Orkestr", intro: "Oğuzcan leads every Orkestr project from discovery and solution architecture through implementation, deployment, and ongoing operation.", work: [["Understand the work", "Turn an unclear business need into users, systems, constraints, risks, and a definition of success."], ["Build the system", "Combine conventional software, data engineering, integrations, browser execution, and AI only where each is appropriate."], ["Keep it working", "Define production ownership, monitoring, maintenance, support, and a safe path for change."]], principle: "The goal is not to sell the most technology. It is to build the simplest system that can reliably produce the required business outcome.", transparent: "From the first working session to production, project responsibility stays directly with Oğuzcan.", cta: "Bring Oğuzcan one system that should work better.", book: "Book a project call",
  },
  de: {
    title: "Team", summary: "Lernen Sie Oğuzcan Ünver kennen, den Gründer, der bei Orkestr Projektklärung, Architektur, Umsetzung, Bereitstellung und betreuten Betrieb verantwortet.", eyebrow: "TEAM", heading: "Orkestr wird von Oğuzcan Ünver geführt.", lead: "Ein verantwortlicher Gründer – vom ersten Gespräch bis zum produktiven System.", role: "Gründer · Orkestr", intro: "Oğuzcan führt jedes Orkestr-Projekt von der Projektklärung und Lösungsarchitektur über die Umsetzung und Bereitstellung bis zum laufenden Betrieb.", work: [["Die Arbeit verstehen", "Aus einem unscharfen Bedarf werden Nutzer, Systeme, Grenzen, Risiken und messbare Erfolgskriterien."], ["Das System bauen", "Klassische Software, Datenverarbeitung, Integrationen, Browserausführung und KI werden nur dort kombiniert, wo sie sinnvoll sind."], ["Den Betrieb sichern", "Produktionsverantwortung, Monitoring, Wartung, Support und ein sicherer Änderungsweg werden festgelegt."]], principle: "Das Ziel ist nicht, möglichst viel Technologie zu verkaufen. Das Ziel ist das einfachste System, das das benötigte Geschäftsergebnis zuverlässig liefert.", transparent: "Vom ersten Arbeitsgespräch bis zum Produktivbetrieb bleibt die Projektverantwortung direkt bei Oğuzcan.", cta: "Bringen Sie Oğuzcan ein System, das besser funktionieren soll.", book: "Projektgespräch buchen",
  },
  tr: {
    title: "Ekip", summary: "Orkestr'de proje keşfi, mimari, geliştirme, devreye alma ve yönetilen işletimi yöneten kurucu Oğuzcan Ünver ile tanışın.", eyebrow: "EKİP", heading: "Orkestr'i Oğuzcan Ünver yönetiyor.", lead: "İlk görüşmeden çalışan sisteme kadar tek ve açık sorumluluk.", role: "Kurucu · Orkestr", intro: "Oğuzcan, her Orkestr projesini ihtiyaçların belirlenmesi ve çözüm mimarisinden geliştirme, devreye alma ve sürekli işletime kadar doğrudan yürütür.", work: [["İşi anla", "Belirsiz bir iş ihtiyacını kullanıcılar, sistemler, kısıtlar, riskler ve başarı ölçütlerine dönüştür."], ["Sistemi geliştir", "Standart yazılımı, veri mühendisliğini, entegrasyonları, tarayıcı işlemlerini ve yapay zekâyı yalnızca uygun oldukları yerde birleştir."], ["Çalışır tut", "Canlı ortam sorumluluğunu, izlemeyi, bakımı, desteği ve güvenli değişiklik yolunu tanımla."]], principle: "Amaç en fazla teknolojiyi satmak değil; gereken iş sonucunu güvenilir biçimde üreten en sade sistemi kurmaktır.", transparent: "İlk çalışma görüşmesinden canlı işletime kadar proje sorumluluğu doğrudan Oğuzcan'da kalır.", cta: "Daha iyi çalışması gereken bir sistemi Oğuzcan'a anlatın.", book: "Proje görüşmesi planla",
  },
};

export function teamPage(locale: PublicLocale = "en"): PublicPage {
  const copy = teamCopy[locale];
  return {
    id: "team", locale, title: copy.title, summary: copy.summary, canonicalPath: publicPagePath("team", locale),
    body: `<main id="main-content"><section class="page-hero team-hero"><p class="section-index">${copy.eyebrow}</p><h1>${copy.heading}</h1><p class="lead">${copy.lead}</p></section><section class="section team-profile"><article class="founder-card"><span class="founder-monogram" aria-hidden="true">OÜ</span><div><p class="section-index">${copy.role}</p><h2>Oğuzcan Ünver</h2><p>${copy.intro}</p></div></article><div class="team-work">${copy.work.map(([title, text], index) => `<article><span>0${index + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join("")}</div></section><section class="section team-principle"><blockquote>${copy.principle}</blockquote><p>${copy.transparent}</p></section><section class="final-cta compact"><h2>${copy.cta}</h2><a class="button button-light" href="${publicPagePath("project", locale)}#book">${copy.book}</a></section></main>`,
  };
}
