import { escapeHtml, publicPagePath, publicProjectSchedulingUrl, type PublicPage } from "./public-site-config.js";

type ProjectCopy = {
  title: string; summary: string; eyebrow: string; heading: string; lead: string; bullets: string[];
  panelLabel: string; panelHeading: string; panelText: string; choose: string; request: string; bookingNote: string; writing: string;
  formLabel: string; formHeading: string; formIntro: string; warning: string; change: string;
  types: Array<[string, string, string]>; outcome: string; outcomePlaceholder: string; context: string; contextPlaceholder: string;
  name: string; email: string; company: string; consent: string; privacy: string; send: string; validation: string; sending: string; success: string; failure: string;
  nextLabel: string; next: Array<[string, string]>; prompts: Record<string, [string, string]>;
};

const copyByLocale: Record<"de" | "tr", ProjectCopy> = {
  de: {
    title: "Projektgespräch buchen", summary: "Buchen Sie ein kurzes Orkestr-Projektgespräch oder beschreiben Sie Ihren Bedarf an Unternehmenssoftware, Modernisierung oder Automatisierung in etwa 60 Sekunden.",
    eyebrow: "PROJEKTKLÄRUNG", heading: "Sprechen wir darüber, was besser funktionieren soll.", lead: "Ein 20-minütiges Gespräch reicht, um das Problem zu verstehen und einen sinnvollen nächsten Schritt zu bestimmen.", bullets: ["Der Geschäftsbedarf genügt als Ausgangspunkt", "Technische Fragen klären wir im Gespräch", "Über den nächsten Schritt entscheiden Sie danach"],
    panelLabel: "20-MINÜTIGES PROJEKTGESPRÄCH", panelHeading: "Beginnen Sie mit einem Gespräch.", panelText: "Erzählen Sie, was Ihr Unternehmen einführen, ersetzen oder vereinfachen muss. Die technischen Fragen stellen wir.", choose: "Termin auswählen", request: "Projektgespräch anfragen", bookingNote: "Der sichere Buchungskalender öffnet sich in einem neuen Tab.", writing: "Lieber schreiben? In 60 Sekunden beschreiben",
    formLabel: "KURZE PROJEKTBESCHREIBUNG", formHeading: "Beschreiben Sie kurz das Wesentliche.", formIntro: "Vier kurze Antworten reichen für die erste Einschätzung. Ergänzen Sie die Informationen, die den Bedarf verständlich machen.", warning: "Senden Sie keine vertraulichen Unterlagen, Zugangsdaten, personenbezogenen Daten oder Produktionszugriffe.", change: "Was soll sich ändern?",
    types: [["build", "Entwickeln", "Neue Website, Shop, Portal oder Anwendung"], ["replace", "Modernisieren", "Altes oder unpassendes Geschäftssystem"], ["automate", "Automatisieren", "Wiederkehrende Arbeit, Datenerfassung oder Monitoring"], ["not-sure", "Noch unklar", "Mit dem Geschäftsproblem beginnen"]],
    outcome: "Was soll das Unternehmen danach tun können?", outcomePlaceholder: "Zum Beispiel: B2B-Kunden sollen online bestellen können, ohne unserem Team eine E-Mail zu senden.", context: "Optional: Was passiert heute?", contextPlaceholder: "Einige Sätze genügen.", name: "Ihr Name", email: "Geschäftliche E-Mail", company: "Unternehmen (optional)", consent: "Ich stimme zu, dass Orkestr diese Angaben verarbeitet und mich zu diesem Projekt kontaktiert.", privacy: "Datenschutzerklärung", send: "Projektbeschreibung senden", validation: "Bitte füllen Sie die vier kurzen Pflichtfelder aus und bestätigen Sie die Kontaktaufnahme.", sending: "Ihre Projektbeschreibung wird gesendet…", success: "Ihre Projektbeschreibung wurde übermittelt. Wir antworten an Ihre geschäftliche E-Mail-Adresse.", failure: "Die Beschreibung konnte nicht gesendet werden. Ihre Eingaben bleiben erhalten; bitte versuchen Sie es erneut oder nutzen Sie den Supportkontakt.",
    nextLabel: "WIE ES WEITERGEHT", next: [["Wir prüfen den Bedarf.", "Wir suchen nach einem konkreten Ergebnis und einem klaren Projektumfang."], ["Wir sprechen.", "Wir fragen nach Nutzern, Systemen, Einschränkungen und Erfolgskriterien."], ["Sie erhalten einen klaren nächsten Schritt.", "Das kann eine Analyse, ein abgegrenztes Angebot oder die Empfehlung eines passenderen Lösungswegs sein."]],
    prompts: { build: ["Optional: Was möchten Sie einführen?", "Was gibt es heute bereits?"], replace: ["Optional: Was muss ersetzt werden?", "Was ist alt, instabil oder passt nicht mehr zum Unternehmen?"], automate: ["Optional: Was wiederholt sich heute?", "Wer erledigt die Arbeit, woher kommen die Informationen und wohin sollen sie gehen?"], "not-sure": ["Optional: Was ist derzeit frustrierend?", "Beschreiben Sie die Situation in einfachen Worten."] },
  },
  tr: {
    title: "Proje Görüşmesi Planla", summary: "Kısa bir Orkestr proje görüşmesi planlayın veya iş yazılımı, modernizasyon ya da otomasyon ihtiyacınızı yaklaşık 60 saniyede anlatın.",
    eyebrow: "PROJE KEŞFİ", heading: "Neyin daha iyi çalışması gerektiğini konuşalım.", lead: "20 dakikalık bir görüşme, sorunu anlamak ve doğru sonraki adımı belirlemek için yeterlidir.", bullets: ["İş ihtiyacını anlatmanız yeterli", "Teknik soruları birlikte netleştiririz", "Sonraki adıma görüşmeden sonra karar verirsiniz"],
    panelLabel: "20 DAKİKALIK PROJE GÖRÜŞMESİ", panelHeading: "Bir görüşmeyle başlayın.", panelText: "İşletmenin neyi başlatması, yenilemesi veya kolaylaştırması gerektiğini anlatın. Teknik soruları biz soralım.", choose: "Uygun zamanı seç", request: "Proje görüşmesi iste", bookingNote: "Güvenli görüşme takvimi yeni sekmede açılır.", writing: "Yazmayı mı tercih edersiniz? 60 saniyede anlatın",
    formLabel: "KISA PROJE ÖZETİ", formHeading: "Temel ihtiyacı kısaca anlatın.", formIntro: "İlk değerlendirme için dört kısa cevap yeterlidir. İhtiyacı anlaşılır kılan bilgileri ekleyin.", warning: "Gizli kayıt, parola, kimlik bilgisi, kişisel veri, özel belge veya canlı sistem erişimi göndermeyin.", change: "Neyin değişmesi gerekiyor?",
    types: [["build", "Geliştir", "Yeni web sitesi, mağaza, portal veya uygulama"], ["replace", "Modernleştir", "Eski veya ihtiyaca uymayan iş sistemi"], ["automate", "Otomatikleştir", "Tekrarlanan iş, veri toplama veya izleme"], ["not-sure", "Emin değilim", "İş sorunuyla başlayın"]],
    outcome: "İşletme ne yapabilir hale gelmeli?", outcomePlaceholder: "Örneğin: B2B müşterileri ekibimize e-posta göndermeden çevrimiçi sipariş verebilmeli.", context: "İsteğe bağlı: Bugün ne oluyor?", contextPlaceholder: "Birkaç cümle yeterlidir.", name: "Adınız", email: "İş e-postası", company: "Şirket (isteğe bağlı)", consent: "Orkestr'in bu bilgileri işlemesini ve proje hakkında benimle iletişime geçmesini kabul ediyorum.", privacy: "Gizlilik bildirimi", send: "Proje özetini gönder", validation: "Dört kısa zorunlu alanı doldurun ve iletişim iznini onaylayın.", sending: "Proje özetiniz gönderiliyor…", success: "Proje özetiniz alındı. İş e-posta adresiniz üzerinden yanıt vereceğiz.", failure: "Özet gönderilemedi. Girdileriniz korunuyor; lütfen tekrar deneyin veya destek iletişimini kullanın.",
    nextLabel: "BUNDAN SONRA", next: [["İhtiyacı inceleriz.", "Somut bir sonuç ve net bir proje kapsamı belirleriz."], ["Görüşürüz.", "Kullanıcıları, sistemleri, kısıtları ve başarı tanımını sorarız."], ["Net bir sonraki adım sunarız.", "Bu; keşif çalışması, kapsamlı teklif ya da daha uygun bir çözüm yolu önerisi olabilir."]],
    prompts: { build: ["İsteğe bağlı: Neyi hayata geçirmek istiyorsunuz?", "Bugün mevcut bir sistem var mı?"], replace: ["İsteğe bağlı: Neyin yenilenmesi gerekiyor?", "Eski, kırılgan veya işe artık uymayan nedir?"], automate: ["İsteğe bağlı: Bugün hangi iş tekrarlanıyor?", "İşi kim yapıyor, bilgi nereden geliyor ve nereye gitmeli?"], "not-sure": ["İsteğe bağlı: Şu anda ne zor geliyor?", "Durumu sade bir dille anlatın."] },
  },
};

function bookingAction(locale: "de" | "tr", env = process.env) {
  const copy = copyByLocale[locale];
  const schedulingUrl = publicProjectSchedulingUrl(env);
  if (schedulingUrl) return `<a class="button button-light booking-primary" href="${escapeHtml(schedulingUrl)}" target="_blank" rel="noreferrer" data-event="project_booking_click">${copy.choose}</a><p class="booking-note">${copy.bookingNote}</p>`;
  return `<a class="button button-light booking-primary" href="#quick-project-form" data-event="project_call_request_click">${copy.request}</a>`;
}

export function localizedProjectIntakePage(locale: "de" | "tr", env = process.env): PublicPage {
  const copy = copyByLocale[locale];
  const privacy = "/privacy";
  const prompts = JSON.stringify(copy.prompts).replace(/</g, "\\u003c");
  const messages = JSON.stringify({ validation: copy.validation, sending: copy.sending, success: copy.success, failure: copy.failure }).replace(/</g, "\\u003c");
  return {
    id: "project", locale, title: copy.title, summary: copy.summary, canonicalPath: publicPagePath("project", locale),
    body: `<main id="main-content" class="project-v4"><section class="project-booking-hero"><div class="project-booking-copy"><p class="section-index">${copy.eyebrow}</p><h1>${copy.heading}</h1><p class="lead">${copy.lead}</p><ul>${copy.bullets.map((item) => `<li>${item}</li>`).join("")}</ul></div><aside class="booking-panel" id="book"><p>${copy.panelLabel}</p><h2>${copy.panelHeading}</h2><p>${copy.panelText}</p>${bookingAction(locale, env)}<a class="booking-secondary" href="#quick-project-form" data-event="project_quick_start">${copy.writing} <span aria-hidden="true">↓</span></a></aside></section>
      <section class="quick-intake-section"><div class="quick-intake-copy"><p class="section-index">${copy.formLabel}</p><h2>${copy.formHeading}</h2><p>${copy.formIntro}</p><p class="legal-note"><strong>${copy.warning}</strong></p></div><form class="workflow-form quick-project-form" id="quick-project-form" novalidate><div class="form-error" id="project-form-error" role="alert" tabindex="-1" hidden></div><input name="intakeMode" type="hidden" value="quick"><fieldset class="project-type-fieldset"><legend><span>1</span> ${copy.change}</legend><div class="project-type-options">${copy.types.map(([value, title, text]) => `<label><input name="projectType" type="radio" value="${value}" required><span><strong>${title}</strong><small>${text}</small></span></label>`).join("")}</div></fieldset><label class="quick-outcome"><span><b>2</b> ${copy.outcome}</span><textarea name="desiredOutcome" required rows="5" maxlength="2400" placeholder="${copy.outcomePlaceholder}"></textarea></label><label class="adaptive-context"><span id="context-label">${copy.context}</span><textarea name="currentSituation" rows="3" maxlength="2000" placeholder="${copy.contextPlaceholder}"></textarea></label><div class="field-grid two quick-contact"><label><span><b>3</b> ${copy.name}</span><input name="contactName" autocomplete="name" required maxlength="120"></label><label><span><b>4</b> ${copy.email}</span><input name="workEmail" type="email" autocomplete="email" required maxlength="160"></label></div><label><span>${copy.company}</span><input name="company" autocomplete="organization" maxlength="160"></label><label class="honeypot" aria-hidden="true"><span>Website</span><input name="companyWebsite" tabindex="-1" autocomplete="off"></label><input name="formStartedAt" type="hidden"><label class="check"><input name="consentToContact" type="checkbox" required><span>${copy.consent} <a href="${privacy}">${copy.privacy}</a></span></label><button class="button submit-workflow" type="submit">${copy.send}</button><p class="form-status" id="project-status" role="status" aria-live="polite"></p><div class="scheduling-handoff" id="project-scheduling-handoff" hidden></div></form></section>
      <section class="project-expectations"><p class="section-index">${copy.nextLabel}</p><ol>${copy.next.map(([title, text], index) => `<li><span>0${index + 1}</span><p><strong>${title}</strong>${text}</p></li>`).join("")}</ol></section>
      <script>(() => { const form=document.getElementById("quick-project-form"), status=document.getElementById("project-status"), error=document.getElementById("project-form-error"), scheduling=document.getElementById("project-scheduling-handoff"), contextLabel=document.getElementById("context-label"), context=form&&form.elements.currentSituation, submit=form&&form.querySelector('button[type="submit"]'); if(!form||!status||!error||!scheduling||!contextLabel||!context||!submit)return; const prompts=${prompts}, messages=${messages}; const reset=()=>{form.elements.formStartedAt.value=String(Date.now())}; reset(); form.addEventListener("change",event=>{if(event.target.name!=="projectType")return; const prompt=prompts[event.target.value]||prompts["not-sure"]; contextLabel.textContent=prompt[0]; context.placeholder=prompt[1]; window.orkestrTrack&&window.orkestrTrack("project_type_selected")}); form.addEventListener("submit",async event=>{event.preventDefault(); error.hidden=true; scheduling.hidden=true; if(!form.reportValidity()){error.textContent=messages.validation;error.hidden=false;error.focus();return} status.textContent=messages.sending;submit.disabled=true; const data=new FormData(form),body=Object.fromEntries(data.entries());body.consentToContact=data.get("consentToContact")==="on"; try{const response=await fetch("/api/public/project-inquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),payload=await response.json().catch(()=>({}));if(!response.ok||payload.ok===false)throw new Error("submit_failed");form.reset();reset();status.textContent=messages.success;if(payload.schedulingUrl){const link=document.createElement("a");link.className="button button-outline";link.href=payload.schedulingUrl;link.target="_blank";link.rel="noreferrer";link.textContent=${JSON.stringify(copy.choose)};scheduling.replaceChildren(link);scheduling.hidden=false}window.orkestrTrack&&window.orkestrTrack("project_quick_submit_success")}catch{error.textContent=messages.failure;error.hidden=false;error.focus();status.textContent=""}finally{submit.disabled=false}})})();</script>
    </main>`,
  };
}
